# Data transformation

Our data for this project on the topic of cervical cancer risk factors was directly downloaded from UCI Machine Learning Repository. The download contains one file only, risk_factors_cervical_cancer.csv. Since the file is in csv format, there is little we need to perform on transforming the data, as R can directly read the data from csv file in an efficient and accurate way.

We would like to present some basic information on the data, including the variable names, variable types, data set shape, and basic observations on the data structure.

## Variable Names and Variable Types
```{r echo = FALSE}
varType <- matrix(c('int','int','int','int','bool','float','float','bool','float','bool','float','bool','int','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','int','int','int','bool','bool','bool','bool','bool','bool','bool','bool','Age','Number of sexual partners','First sexual intercourse (age)','Num of pregnancies','Smokes','Smokes (years)','Smokes (packs/year)','Hormonal Contraceptives','Hormonal Contraceptives (years)','IUD','IUD (years)','STDs','STDs (number)','STDs:condylomatosis','STDs:cervical condylomatosis','STDs:vaginal condylomatosis','STDs:vulvo-perineal condylomatosis','STDs:syphilis','STDs:pelvic inflammatory disease','STDs:genital herpes','STDs:molluscum contagiosum','STDs:AIDS','STDs:HIV','STDs:Hepatitis B','STDs:HPV','STDs: Number of diagnosis','STDs: Time since first diagnosis','STDs: Time since last diagnosis','Dx:Cancer','Dx:CIN','Dx:HPV','Dx','Hinselmann: target variable','Schiller: target variable','Cytology: target variable','Biopsy: target variable'),ncol=2)
colnames(varType) = c('Type', 'Variable Name')
rownames(varType) = 1:36
varType = as.table(varType)
varType
```

Dx: oncology tests on specific diseases. Test on genes and mutations. 

Hinselmann: a test method for cervical cancer by examining the cells on an instrument called colposcope.

Schiller: a preliminary test for cancer of the uterine cervix in which the cervix is painted with an aqueous solution of iodine and potassium iodide.

Cytology: A cytology test is used to look closely at cells and body fluids.

Biopsy: removes a small amount of tissue to examine under a microscope.

## Dataset Shape and Observations

Row number: 858
Column number: 36

Observations: There are values '?' in the dataset, indicating the missing of values. The patients may decided not to answer such specific questions that relates to the specific columns. That could be reasons of privacy concerns or personal misunderstandings. 

Smoke years, Hormonal Contraceptives years, and IUD years values are not integers but floats. This means when doing the survey, patients include months or days into the record. Specific down to months would make the data more specific and possibly help analysis on correlations between these year variables to cervical cancer to be more reliable.

Some variables seem related by their properties. For example, when a patient do not smoke, her smoke years variable would be 0. When a patient did not have any number of diagnosis on STD, the Time since first diagnosis and Time since last diagnosis of STD variables are left to be '?'. This is a logical missing values in this circumstance.